BEGIN;


CREATE TABLE IF NOT EXISTS public.activity
(
    user_id integer NOT NULL,
    book_id integer NOT NULL,
    CONSTRAINT book_views_pkey PRIMARY KEY (user_id, book_id)
);

CREATE TABLE IF NOT EXISTS public.book_impressions
(
    rating_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    book_id integer NOT NULL,
    rating numeric(2, 1) NOT NULL,
    comment text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT book_impressions_pkey PRIMARY KEY (rating_id, user_id, book_id)
);

CREATE TABLE IF NOT EXISTS public.books
(
    book_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title character varying(200) COLLATE pg_catalog."default" NOT NULL,
    author character varying(120) COLLATE pg_catalog."default" NOT NULL,
    genre character varying(40) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT books_pkey PRIMARY KEY (book_id),
    CONSTRAINT book_title UNIQUE (title)
        INCLUDE(title)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    full_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    username character varying(32) COLLATE pg_catalog."default" NOT NULL,
    tg_handle character varying(32) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT user_pkey PRIMARY KEY (user_id),
    CONSTRAINT user_tg_handle_key UNIQUE (tg_handle),
    CONSTRAINT user_username_key UNIQUE (username)
);

ALTER TABLE IF EXISTS public.activity
    ADD CONSTRAINT "book_views.book_id" FOREIGN KEY (book_id)
    REFERENCES public.books (book_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.activity
    ADD CONSTRAINT "book_views.user_id" FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.book_impressions
    ADD CONSTRAINT user_activity FOREIGN KEY (user_id, book_id)
    REFERENCES public.activity (user_id, book_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;

END;